- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: myResourceGroup
      location: eastus2
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: myResourceGroup
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: myResourceGroup
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: myResourceGroup
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: myResourceGroup
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: myResourceGroup
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      ip_configurations:
        - name: ipconfig1
          public_ip_address_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1AJfuxnpI7KoEewFnZMHSVtwhtM8/xOYUU2H09kzdjh8us5WqYOyKM9kzAO4SLBc60Oow5MbFrpQ+vphVLrrG55ahRAsKofJSaIztlksa/ntx7x+h8bP5nH3s8n8EN1z9zDgasE/ye/09dyPVVmppRj2P0pFWCTBpv+XfFJ+TFwy/HLwzaTprCNcQ2lkICdcrEW5NIjg8RJLSqoj5nvEw/rs8bPwoXiS0RaVLwhifXWa8zXNgDl7OH2ZdYKKSJEQLu4/JJhslsRQ7bjqdrdszos3Z/EJVhBFdfl7Beyf/pAJswlngFXGUazL7BleyLI3Uka1E4jlcZTXjuHX0v9kGqCxv027bVpKjbZM16rJaQmaKApmcmz53Wyw3eMixTxEoiA9AM+HQ8OIRz7WacZxRm4Ju3J9xqoNHBmAQkFmVtgD2wH1JOcy2mqwLF3xq0dQaJcAelN9U/N5AyV1deUQgbqbd4iFRnfAaLNaMxo+dbuM4sIPaCBHwdXp0Z59N47NFROTiq5cYXdmdS6fc5q4rWvEUQCveQulF9nxISL+GM6rFjm41CAMLlP2q89ZWOR6PBnJ2fKWYyjLIpkkOxOpLR2ZfqMgYoVERLYthzHj1YC2bH4CpBAHvRbXJzFPYBASMlFshZ30se0sWwtrXLcYe0euIA9NdFKbYMFduLTl3iQ== azureuser@QuickstartAnsible-vm"
      network_interfaces: myNIC
      image:
        offer: 0001-com-ubuntu-server-jammy
        publisher: Canonical
        sku: 22_04-lts
        version: latest
